{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.dosukoi-juku",
    "module": "license-report-gradle-plugin",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "license-report-gradle-plugin-0.0.1-SNAPSHOT.jar",
          "url": "license-report-gradle-plugin-0.0.1-SNAPSHOT.jar",
          "size": 75039,
          "sha512": "32fbe3794336d9dfd32e3b9885c96d7bb5d8501e173f6cc7bd8c05cab2e04b8b4de15c7182801ea081bcfbb3306946b4cba532c9f32bef368d440d12b55b6042",
          "sha256": "708f6593448fe6c7c290321554445431138ea6d752ea2e94d8844e7336a2b066",
          "sha1": "3581cc10cafc77dfa36aedd39000bda12a43dfad",
          "md5": "96a990182e43776a86e465c87bb24299"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.19.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.91.0-RC1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "license-report-gradle-plugin-0.0.1-SNAPSHOT.jar",
          "url": "license-report-gradle-plugin-0.0.1-SNAPSHOT.jar",
          "size": 75039,
          "sha512": "32fbe3794336d9dfd32e3b9885c96d7bb5d8501e173f6cc7bd8c05cab2e04b8b4de15c7182801ea081bcfbb3306946b4cba532c9f32bef368d440d12b55b6042",
          "sha256": "708f6593448fe6c7c290321554445431138ea6d752ea2e94d8844e7336a2b066",
          "sha1": "3581cc10cafc77dfa36aedd39000bda12a43dfad",
          "md5": "96a990182e43776a86e465c87bb24299"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "license-report-gradle-plugin-0.0.1-SNAPSHOT-sources.jar",
          "url": "license-report-gradle-plugin-0.0.1-SNAPSHOT-sources.jar",
          "size": 9453,
          "sha512": "ecf60f32b50d7a13630d93244e6df207025a2c84e252028c733ec8f04f509e997bab2238c319eec05cc559324f08eaae18a7645504965781b6164e805a932d37",
          "sha256": "302757c994460999a3dc47a695d1a55b003f2d3b24a03f694ec7aaeca98afbac",
          "sha1": "2dbf9e1123c7367e4c572316e76d1201ed2236fd",
          "md5": "cba83b5f17e45da4def91c1f9093e75d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "license-report-gradle-plugin-0.0.1-SNAPSHOT-javadoc.jar",
          "url": "license-report-gradle-plugin-0.0.1-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "ae8855b30d70317436886d77a8b59fd2081c149bfccb7ab5d1acfc46fbb37bad87eb22ec3cea3c4cc90fb6f059f972aa5f5738b7c3e165b6e82f17a73ec3b0fa",
          "sha256": "fcb9111363bd17e623c7eb97b801c89bd4a872df6ccb86284bb4bde717dca3dc",
          "sha1": "c6d6ea8e6ebee9df80ac92ccadfece73ce081c52",
          "md5": "02e983e81fe60c79560f913b50fddfd2"
        }
      ]
    }
  ]
}
